# Generated by Django 4.0.1 on 2022-02-04 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('callsign', models.CharField(max_length=100)),
                ('online', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProfileRoomLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.ForeignKey(blank=True, db_column='profile_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.profile')),
                ('room_id', models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.room')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pending', models.BooleanField(default=True)),
                ('friend_id', models.ForeignKey(blank=True, db_column='friend_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='friend_id', to='chat.profile')),
                ('profile_id', models.ForeignKey(blank=True, db_column='profile_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_id', to='chat.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='connections',
            field=models.ManyToManyField(blank=True, through='chat.ProfileLink', to='chat.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='rooms',
            field=models.ManyToManyField(blank=True, through='chat.ProfileRoomLink', to='chat.Room'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('profile_id', models.ForeignKey(db_column='profile_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.profile')),
                ('room_id', models.ForeignKey(db_column='room_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.room')),
            ],
        ),
    ]
