# Generated by Django 4.0.1 on 2022-01-31 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_room_id_alter_message_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_id',
        ),
        migrations.AddField(
            model_name='message',
            name='profile_id',
            field=models.ForeignKey(db_column='profile_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.profile'),
        ),
    ]
