# Generated by Django 4.0.1 on 2022-01-27 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilelink',
            name='pending',
            field=models.BooleanField(default=True),
        ),
    ]
