# Generated by Django 4.0.1 on 2022-01-28 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_profilelink_pending'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilelink',
            name='profile_id',
            field=models.ForeignKey(blank=True, db_column='profile_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_id', to='chat.profile'),
        ),
    ]
