# Generated by Django 4.0.1 on 2022-01-29 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_profilelink_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='user_id',
        ),
        migrations.AddField(
            model_name='profile',
            name='room_id',
            field=models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.room'),
        ),
    ]
