# Generated by Django 4.0.1 on 2022-01-29 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_room_user_id_profile_room_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileRoomLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='room_id',
        ),
        migrations.AddField(
            model_name='room',
            name='profiles',
            field=models.ManyToManyField(blank=True, through='chat.ProfileRoomLink', to='chat.Profile'),
        ),
        migrations.AddField(
            model_name='profileroomlink',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.profile'),
        ),
        migrations.AddField(
            model_name='profileroomlink',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.room'),
        ),
    ]
