# Generated by Django 4.0.1 on 2022-01-29 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_profileroomlink_remove_profile_room_id_room_profiles_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profileroomlink',
            old_name='profile',
            new_name='profile_id',
        ),
        migrations.RenameField(
            model_name='profileroomlink',
            old_name='room',
            new_name='room_id',
        ),
        migrations.AlterField(
            model_name='profileroomlink',
            name='profile_id',
            field=models.ForeignKey(blank=True, db_column='profile_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.profile'),
        ),
        migrations.AlterField(
            model_name='profileroomlink',
            name='room_id',
            field=models.ForeignKey(blank=True, db_column='room_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.room'),
        ),
    ]
